name: election_blockchain
description: "Blockchain technology"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  hive: ^2.2.3
  lottie: ^3.1.0
  shadow_overlay: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
